#!/bin/bash

# Check if we're not committing to a detached state
if [ ! $(git symbolic-ref HEAD) ]
then
  echo "You're not on a branch, checkout a branch before committing"
  exit 1
fi

# Check we're not committing to master
protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    read -p "You're about to commit to master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
